apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: generatedata
  name: generatedata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: generatedata
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: generatedata
    spec:
      containers:
      - env:
        - name: GD_DB_HOSTNAME
          value: mysql
        - name: GD_DB_NAME
          value: generatedata
        - name: GD_DB_USERNAME
          value: root
        image: mvisonneau/generatedata:latest
        imagePullPolicy: ""
        name: generatedata
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
